api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Application'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            api_key:
                name: Authorization
                type: header
    title: Symfony 5 Api Platform
    version: 1.0
    show_webby: false
